language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - $HOME/.m2


android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-26

  licenses:
    - '.+'