language: android
jdk: oraclejdk8
sudo: false

before_install:
  - pip install --user codecov

after_success:
  - codecov

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-26

  licenses:
    - '.+'